CREATE TABLE MEMBER (
	MEMBER_NO	    NUMBER PRIMARY KEY NOT NULL, -- 회원식별자
	MEMBER_NAME	    VARCHAR2(20) NOT NULL, -- 이름
	MEMBER_ID	    VARCHAR2(50) NOT NULL, -- 아이디
	MEMBER_PWD	    VARCHAR2(16) NOT NULL, -- 비밀번호
	MEMBER_PHONE	VARCHAR2(13) NULL, -- 연락처
    MEMBER_DATE     SYSDATE NULL, -- 회원등록날짜
	ADMIN_CHECK	    VARCHAR2(20) NOT NULL, -- Y.일반유저 N.관리자
	RECOM_COUNT	    NUMBER DEFAULT 0, -- 추천받은 횟수
	MEMBER_STATUS	VARCHAR2(1)	NULL, --B.블라인드 Y.일반 D.삭제된계정
	AD_AGREE	    VARCHAR2(1)	NULL, -- Y.동의 N. 비동의
	RECOM_CODE	    VARCHAR2(10) NOT NULL,
	MEMBER_POINT	NUMBER NULL,
);

CREATE SEQUENCE MEMBER_NO_SEQ
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;

INSERT INTO MEMBER(MEMBER_NO, MEMBER_NAME, MEMBER_ID, MEMBER_PHONE)
VALUES (MEMBER_NO_SEQ.NEXTVAL, ?, ? ,? );







CREATE TABLE ROOM (
	ROOM_NO	            NUMBER PRIMARY KEY NOT NULL, -- 룸테이블 식별자
	ROOM_NAME	        VARCHAR2(20) NOT NULL, -- 룸명
	ROOM_TYPE	        VARCHAR2(2) NULL, -- 1. 개인 2. 단체
	ROOM_CAPACITY	    NUMBER NOT NULL, -- 수용인원
	ROOM_INFORMATION    VARCHAR2(300) NOT NULL, -- 이용정보
	ROOM_FILEPATH	    VARCHAR2(1000) NULL -- 사진저장경로
);

CREATE SEQUENCE ROOM_NO_SEQ
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;







CREATE TABLE PRODUCT (
	PRODUCT_NO	     NUMBER	PRIMARY KEY NOT NULL, -- 상품 식별자
	PRODUCT_ROOM_NO	 NUMBER	REFERENCES PRODUCT (ROOM_NO), -- 룸테이블 식별자
	ROOM_TIME	     SYSDATE NULL,
	ROOM_CONDITION	 VARCHAR2(10) NOT NULL, -- Y 이용가능. O 이용중. R 수리중.
	ROOM_PRICE	     NUMBER	NOT NULL, -- 상품가격
	ROOM_INFO	     VARCHAR2(500) NULL, -- 시설정보
	RESERVATION_DATE SYSDATE NOT NULL, -- 예약일
	PAYMENT_DATE	 SYSDATE -- 결제일
);

CREATE SEQUENCE PRODUCT_NO_SEQ
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;







CREATE TABLE BOARD(
	BOARD_NO	    NUMBER PRIMARY KEY NOT NULL, -- 게시판 식별자
	BOARD_MEMBER_NO	NUMBER REFERENCES BOARD (MEMBER_NO), -- 회원 식별자
	CATEGORY	    VARCHAR2(100) NOT NULL, -- 카테고리
	BOARD_TITLE	    VARCHAR2(200) NOT NULL, -- 제목
	BOARD_CONTENT	VARCHAR2(4000) NOT NULL, -- 내용
	BOARD_COUNT	    NUMBER NULL, -- 조회수
    BOARD_ANSWER	VARCHAR2(10) NOT NULL, -- 답변여부 DEFAULT N
	BOARD_DATE	    SYSDATE	NOT NULL, -- 작성일
    ANSWER_CONTENT	VARCHAR2(200) NULL, -- 답변내용
	MEMBER_NAME	    VARCHAR2(20) NOT NULL -- 작성자
);

CREATE SEQUENCE BOARD_NO_SEQ
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;








CREATE TABLE CATEGORY (
	CATEGORY	    VARCHAR2(200)	NOT NULL,
	CATEGORY_NAME	VARCHAR2(200)	NOT NULL
);

CREATE TABLE NOTICE (
	NOTICE_NO	        NUMBER	PRIMARY KEY NOT NULL, -- 공지사항 식별자
	NOTICE_MEMBER_NO	NUMBER	REFERENCES NOTICE (MEMBER_NO), -- 회원 식별자
	NOTICE_TITLE	    VARCHAR2(200)	NOT NULL,
	NOTICE_CONTENT	    VARCHAR2(4000)	NOT NULL,
);

CREATE SEQUENCE NOTICE_NO_SEQ
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;








CREATE TABLE COUPON (
	COUPON_NO	    NUMBER	PRIMARY KEY NOT NULL, -- 가용쿠폰 식별자
	COUPON_NAME	    VARCHAR2(1000)	NULL,
	COUPON_VALID	VARCHAR2(20) DEFAULT N	NOT NULL, -- Y. 사용됨 N. 아직
	COUPON_PRICE	NUMBER	NOT NULL,
	COUPON_DATE	    DATE	NOT NULL, -- SYSDATE 기준 한달  = SYSDATE + 30
	COUPON_CODE	    VARCHAR2(40)	NOT NULL -- 앞에 영어 4글자 후 숫자 4글자
);

CREATE SEQUENCE COUPON_NO_SEQ
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;








CREATE TABLE RESERVATION (
	RESERVATION_NO	        NUMBER	PRIMARY KEY NOT NULL, -- 예약식별자
	MEMBER_NO	            NUMBER	PRIMARY KEY NOT NULL, --회원식별자
	PRODUCT_NO	            NUMBER	PRIMARY KEY NOT NULL, -- 상품식별자
	RESERVATION_NAME	    VARCHAR2(100)	NOT NULL,
	RESERVATION_EMAIL	    VARCHAR(255)	NULL,
	RESERVATION_PHONE	    VARCHAR2(100)	NULL,
	RESERVATION_PERSONNEL	NUMBER	NOT NULL,
	RESERVATION_DATE	    DATE	NOT NULL,
	RESERVATION_TIME	    VARCHAR(255)	NULL,
	PAYMENT_METHOD	        VARCHAR(255)	NULL,
	PAYMENT_DATE	        DATE	NOT NULL,
	PAYMENT_PRICE	        NUMBER	NOT NULL,
	RESERVATION_CONDITION	VARCHAR2(20)	DEFAULT Y	NOT NULL, -- Y는 예약,C는 취소 ,O사용됨
	PAYMENT_INFO	        VARCHAR2(20) NULL -- C는 카드,   P현금 , T 무통장, D 현장
);

CREATE SEQUENCE RESERVATION_NO_SEQ
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;







ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "ROOM" ADD CONSTRAINT "PK_ROOM" PRIMARY KEY (
	"ROOM_NO"
);

ALTER TABLE "PRODUCT_TABLE" ADD CONSTRAINT "PK_PRODUCT_TABLE" PRIMARY KEY (
	"PRODUCT_NO"
);

ALTER TABLE "QnA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"CATEGORY"
);

ALTER TABLE "Notice" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "COUPON" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY (
	"COUPON_NO"
);

ALTER TABLE "RESERVATION" ADD CONSTRAINT "PK_RESERVATION" PRIMARY KEY (
	"RESERVATION_NO"
);

